seed_everything: 77
# /local/data/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p10/p10000032/s53911762
trainer:
  default_root_dir: ./results/image_disease_classification_77
  accelerator: cuda
  devices: 1
  log_every_n_steps: 1
  max_epochs: 100
  callbacks:
  - class_path: lightning.pytorch.callbacks.RichProgressBar
  - class_path: lightning.pytorch.callbacks.EarlyStopping
    init_args:
        monitor: 'val_loss'
        patience: 4
        mode: 'min'  # or 'max' depending on your metric
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
        monitor: 'val_loss'
        mode: 'min'  # or 'max' depending on your metric
        save_top_k: 100  # save only the best checkpoint
        dirpath: './results/image_disease_classification_77/checkpoints/'
        filename: 'best_val_loss-{epoch:02d}-{val_loss:.4f}'
  

data: # data.moudle.DataModule
  train_dataset:
    class_path: data.image.dataset_class.ImageDataset_all
    init_args:
      dataframe_path: /local/home/mikailk/fairness_on_embeddings/dataframes/mimic_train_df.csv
      path_image: /local/data/physionet.org/files/mimic-cxr-jpg/2.0.0/
      transform:
        class_path: torchvision.transforms.Compose
        init_args:
          transforms:
          - class_path: torchvision.transforms.RandomHorizontalFlip
          - class_path: torchvision.transforms.RandomRotation
            init_args:
              degrees: 15
          - class_path: torchvision.transforms.Resize
            init_args:
              size: [256,256]
          - class_path: torchvision.transforms.CenterCrop
            init_args:
              size: 256
          - class_path: torchvision.transforms.ToTensor
          - class_path: torchvision.transforms.Normalize
            init_args:
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
  val_dataset:
    class_path: data.image.dataset_class.ImageDataset_all
    init_args:
      dataframe_path: /local/home/mikailk/fairness_on_embeddings/dataframes/mimic_validation_df.csv
      path_image: /local/data/physionet.org/files/mimic-cxr-jpg/2.0.0/
      transform:
        class_path: torchvision.transforms.Compose
        init_args:
          transforms:
          - class_path: torchvision.transforms.Resize
            init_args:
              size: [256,256]
          - class_path: torchvision.transforms.CenterCrop
            init_args:
              size: 256
          - class_path: torchvision.transforms.ToTensor
          - class_path: torchvision.transforms.Normalize
            init_args:
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
  test_dataset:
    class_path: data.image.dataset_class.ImageDataset_all
    init_args:
      dataframe_path: /local/home/mikailk/fairness_on_embeddings/dataframes/mimic_test_df.csv
      path_image: /local/data/physionet.org/files/mimic-cxr-jpg/2.0.0/
      transform:
        class_path: torchvision.transforms.Compose
        init_args:
          transforms:
          - class_path: torchvision.transforms.Resize
            init_args:
              size: [256,256]
          - class_path: torchvision.transforms.CenterCrop
            init_args:
              size: 256
          - class_path: torchvision.transforms.ToTensor
          - class_path: torchvision.transforms.Normalize
            init_args:
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
  batch_size: 48
  num_workers: 40
  prediction_on: "test"


model: # models.module.CLS
  model:
    class_path: models.image.models.DensNetWithHead
    init_args:
      hidden_layer_sizes: [768, 256]
      dropout_rate: 0.3
      num_classes: 14
  criterion: # torch.nn.BCEWithLogitsLoss
    class_path: torch.nn.BCEWithLogitsLoss
  weight_decay: 0.00001
  prediction_on: "test"
  save_probabilities_path: ./results/image_disease_classification_77/probabilities